#### Numpy is like a supercharged version of lists in Python. It allows you to do mathematical operations on large amounts of data very quickly and efficiently. It provides support for arrays, matrices, and a collection of mathematical functions to operate on these arrays.

**importing numpy**

In [84]:
import numpy as np

#### understanding the importance of numpy

In [85]:
import time

**with normal python**

In [86]:
scores = [78, 85, 62, 90, 88, 76]

start_time = time.time()
average_score = sum(scores) / len(scores)
end_time = time.time()
python_time = end_time - start_time

print("Average score using normal Python methods:", average_score)
print("Time taken using normal Python methods:", python_time)

Average score using normal Python methods: 79.83333333333333
Time taken using normal Python methods: 3.409385681152344e-05


**with numpy**

In [87]:
scores = np.array([78, 85, 62, 90, 88, 76])

start_time = time.time()
average_score = np.mean(scores)
end_time = time.time()
numpy_time = end_time - start_time

print("Average score using numpy:", average_score)
print("Time taken using numpy:", numpy_time)


Average score using numpy: 79.83333333333333
Time taken using numpy: 7.796287536621094e-05


#### np.arange():

np.arange() is a function in NumPy used to create an array with regularly spaced values within a specified range. Its syntax is:

**numpy.arange([start, ]stop, [step, ]dtype=None)**

- `start`: Optional. The start of the interval (inclusive). Default is 0.
- `stop`: The end of the interval (exclusive).
- `step`: Optional. The step size between values. Default is 1.
- `dtype`: Optional. The data type of the array. If not specified, the data type is inferred from the other input arguments.

In [88]:
# Create an array from 0 to 9
arr = np.arange(10)
print(arr)  # Output: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


#### NumPy Arrays (ndarrays):

NumPy arrays, or ndarrays, are the primary data structure used in NumPy. They are homogeneous collections of elements with fixed dimensions and have many similarities to Python lists but with additional functionality optimized for numerical computing.

In [89]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)       # Output: [1 2 3 4 5]
print(arr_1d[0])    # Output: 1


# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Properties of nd Arrays

**1. Shape:**

The shape of an ndarray describes the size of each dimension of the array. It is represented as a tuple of integers indicating the number of elements along each dimension.

In [90]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Print the shape
print("Shape of the array:", arr_2d.shape)  # Output: (2, 3)

Shape of the array: (2, 3)


**2. Data Type (dtype):**

The data type of an ndarray specifies the type of elements stored in the array. NumPy arrays can hold elements of different types such as integers, floats, booleans, etc.

In [91]:
# Create an array with a specific data type
arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float32)
# Print the data type
print("Data type of the array:", arr_float.dtype)  # Output: float32

Data type of the array: float32


**3. Size:**

The size of an ndarray is the total number of elements in the array. It is equal to the product of the dimensions of the array.

In [92]:
# Create a 3D array
arr_3d = np.zeros((2, 3, 4))
print(arr_3d)

# Print the size
print("Size of the array:", arr_3d.size)  # Output: 24 (2 * 3 * 4)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Size of the array: 24


**4. Number of Dimensions (ndim):**

The ndim attribute of an ndarray specifies the number of dimensions or axes of the array.

In [93]:
# Create a 4D array
arr_4d = np.ones((2, 3, 4, 5))

# Print the number of dimensions
print("Number of dimensions:", arr_4d.ndim)  # Output: 4

Number of dimensions: 4


**5. Itemsize:**

The itemsize attribute of an ndarray specifies the size of each element in bytes.

In [94]:
# Create an array of integers
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)
# Print the item size
print("Size of each element (in bytes):", arr_int.itemsize)  # Output: 8 (for 64-bit integer)

int64
Size of each element (in bytes): 8


**NumPy Data Types (dtypes):**

NumPy provides a variety of data types to represent different kinds of numerical data. These data types are important for controlling memory usage and ensuring data integrity in numerical computations.

**Common NumPy Data Types:**

- **int**: Integer (default size depends on the platform).
- **float**: Floating point number (default size depends on the platform).
- **bool**: Boolean (True or False).
- **complex**: Complex number with real and imaginary parts.
- **uint**: Unsigned integer (no negative values).

**Specifying Data Types:**

You can specify the data type of an ndarray using the `dtype` parameter of NumPy functions or by providing the data type as an argument to the array creation functions.

In [95]:
# Create an array with a specific data type
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1.1, 2.2, 3.3], dtype=np.float64)

print("Data type of arr_int32:", arr_int32.dtype)   # Output: int32
print("Data type of arr_float64:", arr_float64.dtype)   # Output: float64

Data type of arr_int32: int32
Data type of arr_float64: float64


**Impact of Precision on Memory Usage:**

In [96]:
# Create arrays with different data types
arr_float32 = np.array([1.1, 2.2, 3.3], dtype=np.float32)
arr_float64 = np.array([1.1, 2.2, 3.3], dtype=np.float64)

print("Memory usage of arr_float32:", arr_float32.itemsize * arr_float32.size, "bytes")  # Output: 12 bytes (3 elements * 4 bytes/element)
print("Memory usage of arr_float64:", arr_float64.itemsize * arr_float64.size, "bytes")  # Output: 24 bytes (3 elements * 8 bytes/element)

Memory usage of arr_float32: 12 bytes
Memory usage of arr_float64: 24 bytes


## np.zeros, np.ones, np.full:

**np.zeros:**

`np.zeros` creates an array filled with zeros. It takes the shape of the desired array as input and returns an array of that shape filled with zeros.

Syntax:
```python
numpy.zeros(shape, dtype=float)
```

- `shape`: The shape of the array (tuple of integers).
- `dtype`: Optional. The data type of the array. Default is `float`.

In [97]:
# Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


**np.ones:**

`np.ones` creates an array filled with ones. Similar to `np.zeros`, it takes the shape of the desired array as input and returns an array of that shape filled with ones.

Syntax:
```python
numpy.ones(shape, dtype=None)
```

- `shape`: The shape of the array (tuple of integers).
- `dtype`: Optional. The data type of the array. If not specified, the default is determined by the data type of `1`.

In [98]:
# Create a 3x2 array filled with ones
ones_array = np.ones((3, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**np.full:**

`np.full` creates an array filled with a specified constant value. It takes the shape of the desired array and the constant value as input and returns an array of that shape filled with the specified value.

Syntax:
```python
numpy.full(shape, fill_value, dtype=None)
```

- `shape`: The shape of the array (tuple of integers).
- `fill_value`: The constant value to fill the array with.
- `dtype`: Optional. The data type of the array. If not specified, the default is determined by the data type of `fill_value`.


In [99]:
# Create a 2x2 array filled with 5
full_array = np.full((2, 2), 4.5)
print(full_array)

[[4.5 4.5]
 [4.5 4.5]]


## Array Operations - NumPy

**1. Arithmetic Operations:**

In [100]:
# Addition
arr_sum = np.add([1, 2, 3], [4, 5, 6])
print("Addition:", arr_sum)  # Output: [5 7 9]

# Subtraction
arr_diff = np.subtract([5, 6, 7], [2, 3, 1])
print("Subtraction:", arr_diff)  # Output: [3 3 6]

# Multiplication
arr_prod = np.multiply([2, 3, 4], [3, 4, 5])
print("Multiplication:", arr_prod)  # Output: [ 6 12 20]

# Division
arr_div = np.divide([10, 12, 14], [2, 3, 2])
print("Division:", arr_div)  # Output: [5. 4. 7.]

# Modulus
arr_mod = np.mod([10, 11, 12], [3, 4, 5])
print("Modulus:", arr_mod)  # Output: [1 3 2]

# Exponentiation
arr_pow = np.power([2, 3, 4], [2, 3, 2])
print("Exponentiation:", arr_pow)  # Output: [ 4 27 16]

Addition: [5 7 9]
Subtraction: [3 3 6]
Multiplication: [ 6 12 20]
Division: [5. 4. 7.]
Modulus: [1 3 2]
Exponentiation: [ 4 27 16]


**2. Relational Operations:**

In [101]:
# Create sample arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 2, 4, 3])

# Equal
print("Equal:", arr1 == arr2)  # Output: [False  True False False]

# Not Equal
print("Not Equal:", arr1 != arr2)  # Output: [ True False  True  True]

# Greater Than
print("Greater Than:", arr1 > arr2)  # Output: [False False False  True]

# Greater Than or Equal To
print("Greater Than or Equal To:", arr1 >= arr2)  # Output: [False  True False  True]

# Less Than
print("Less Than:", arr1 < arr2)  # Output: [ True False False False]

# Less Than or Equal To
print("Less Than or Equal To:", arr1 <= arr2)  # Output: [ True  True  True False]

Equal: [False  True False False]
Not Equal: [ True False  True  True]
Greater Than: [False False False  True]
Greater Than or Equal To: [False  True False  True]
Less Than: [ True False  True False]
Less Than or Equal To: [ True  True  True False]


## Indexing and Slicing for 1D Arrays

**1. Indexing:**

Indexing refers to accessing individual elements of an array using their position (index) within the array. In NumPy, indexing starts from 0, so the first element has index 0, the second element has index 1, and so on.

In [102]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Access individual elements using indexing
print("First element:", arr[0])   # Output: 1
print("Second element:", arr[1])  # Output: 2
print("Last element:", arr[-1])   # Output: 5 (negative indexing)

First element: 1
Second element: 2
Last element: 5


**2. Slicing:**

Slicing allows you to extract a subset of elements from an array by specifying a range of indices. The basic syntax for slicing is `start:stop:step`, where `start` is the starting index (inclusive), `stop` is the ending index (exclusive), and `step` is the step size.

In [103]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Slice elements from index 1 to index 3 (exclusive)
print("Slice:", arr[1:3])  # Output: [2 3]

# Slice elements from index 0 to index 4 with step size 2
print("Slice with step:", arr[0:4:2])  # Output: [1 3]

Slice: [2 3]
Slice with step: [1 3]


**3. Negative Indexing:**

Negative indexing allows you to access elements from the end of the array by specifying negative indices. `-1` refers to the last element, `-2` refers to the second last element, and so on.

In [104]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Access the last element using negative indexing
print("Last element:", arr[-1])  # Output: 5

Last element: 5


**4. Slicing with Omitted Indices:**

You can omit any of the slicing parameters to use default values. Omitting `start` defaults to 0, omitting `stop` defaults to the end of the array, and omitting `step` defaults to 1.

In [105]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Slice elements from the beginning to index 3 (exclusive)
print("Slice with omitted start:", arr[:3])  # Output: [1 2 3]

# Slice elements from index 2 to the end
print("Slice with omitted stop:", arr[2:])  # Output: [3 4 5]

# Slice elements with step size 2
print("Slice with omitted step:", arr[::2])  # Output: [1 3 5]

Slice with omitted start: [1 2 3]
Slice with omitted stop: [3 4 5]
Slice with omitted step: [1 3 5]



## Indexing and Slicing for 2D Arrays

**1. Indexing:**

Indexing refers to accessing individual elements of an array using their position (index) within the array. In a 2D array, indexing is done using row and column indices.

In [106]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Access individual elements using indexing
print("Element at (0, 0):", arr[0, 0])  # Output: 1
print("Element at (1, 2):", arr[1, 2])  # Output: 6

Element at (0, 0): 1
Element at (1, 2): 6


**2. Slicing:**

Slicing allows you to extract a subset of elements from an array by specifying ranges of row and column indices. The basic syntax for slicing is `start:stop:step`, where `start` is the starting index (inclusive), `stop` is the ending index (exclusive), and `step` is the step size.

In [107]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice elements from rows 0 to 1 (exclusive) and columns 1 to 2 (exclusive)
print("Slice:", arr[0:2, 1:3])


# Modify slice
arr[0:2, 1:3] = [[10, 20], [30, 40]]
print("Modified array after slicing:", arr)

Slice: [[2 3]
 [5 6]]
Modified array after slicing: [[ 1 10 20]
 [ 4 30 40]
 [ 7  8  9]]


**3. Negative Indexing:**

Negative indexing can also be used in 2D arrays to access elements from the end of the array.

In [108]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Access the last element using negative indexing
print("Last element:", arr[-1, -1])  # Output: 9

Last element: 9


**4. Slicing with Omitted Indices:**

You can omit any of the slicing parameters to use default values. Omitting `start` defaults to 0, omitting `stop` defaults to the end of the array, and omitting `step` defaults to 1.

In [109]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice elements from rows 1 to the end and all columns
print("Slice with omitted start and stop:", arr[1:])

# Slice elements from all rows and columns 0 to 1 (exclusive) with step size 2
print("Slice with omitted step:", arr[:, 0:2:2])

Slice with omitted start and stop: [[4 5 6]
 [7 8 9]]
Slice with omitted step: [[1]
 [4]
 [7]]


## Playing with Arrays

**1. Transposing Arrays:**

Transposing an array means exchanging its rows and columns. In NumPy, you can transpose an array using the `T` attribute or the `transpose()` function.

In [110]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Transpose the array
transposed_arr = arr_2d.T
print("Transposed array:")
print(transposed_arr)

Transposed array:
[[1 4]
 [2 5]
 [3 6]]


**2. Swapping Axes:**

Swapping axes means rearranging the dimensions of an array. You can swap axes using the `swapaxes()` function.

In [111]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Swap axes
swapped_arr = arr_2d.swapaxes(0,1)
print("Swapped array:")
print(swapped_arr)

Swapped array:
[[1 4]
 [2 5]
 [3 6]]


**3. Pseudo-random Number Generation:**

NumPy provides various functions for generating pseudo-random numbers. These functions are located in the `numpy.random` module. You can generate random numbers from different distributions, such as uniform, normal, binomial, etc.

In [112]:
# Pseudo-random Number Generation in 1D Array:

# Generate 5 random integers between 1 and 10
random_integers = np.random.randint(1, 10, size=5)
print("Random integers (1D):", random_integers)

# Generate 5 random numbers from a normal distribution
random_normal = np.random.normal(size=5)
print("Random numbers from normal distribution (1D):", random_normal)

Random integers (1D): [5 2 6 9 6]
Random numbers from normal distribution (1D): [-1.75051324  0.87108052  0.40417441  0.8303278  -0.17934444]


In [113]:
# Pseudo-random Number Generation in 2D Array:

# Generate a 2D array of shape (3, 3) with random integers between 1 and 10
random_integers_2d = np.random.randint(1, 10, size=(3, 3))
print("Random integers (2D):")
print(random_integers_2d)

# Generate a 2D array of shape (3, 3) with random numbers from a normal distribution
random_normal_2d = np.random.normal(size=(3, 3))
print("Random numbers from normal distribution (2D):")
print(random_normal_2d)

Random integers (2D):
[[7 9 2]
 [7 4 9]
 [8 8 7]]
Random numbers from normal distribution (2D):
[[-0.23415556 -0.60817243  1.41482822]
 [-2.8701745  -0.89920373  1.6542656 ]
 [ 0.40375716  0.74105997 -0.2603282 ]]


## Operations on 2D Arrays

**1. Matrix Multiplication (`np.matmul()`):**

Matrix multiplication is a fundamental operation in linear algebra, where you multiply two matrices to obtain a new matrix. In NumPy, you can perform matrix multiplication using the `np.matmul()` function.

In [114]:
# Define matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.matmul()
result = np.matmul(matrix_a, matrix_b)
print("Matrix Multiplication:")
print(result)

Matrix Multiplication:
[[19 22]
 [43 50]]


**2. Reshaping (`np.reshape()`):**

Reshaping an array means changing the shape of the array without changing its data. It's useful for converting arrays between different dimensions or rearranging their layout.

In [115]:
# Reshaping an array
arr = np.arange(1, 10)  # 1D array from 1 to 9
print(arr)
reshaped_arr = arr.reshape((3, 3))  # Reshape to a 3x3 matrix
print("Reshaped array:")
print(reshaped_arr)

[1 2 3 4 5 6 7 8 9]
Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**3. Transpose (`np.transpose()`):**

Transposing a matrix means flipping its rows with its columns. In NumPy, you can obtain the transpose of a matrix using the `np.transpose()` function or the `.T` attribute.

In [116]:
# Transposing a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transposed_matrix = np.transpose(matrix)
print("Transposed matrix:")
print(transposed_matrix)

Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


**4. Aggregate Functions:**

Aggregate functions in NumPy are functions that operate on arrays and return a single value, summarizing the data in some way. Common aggregate functions include `np.sum()`, `np.max()`, `np.min()`, `np.mean()`, etc.

In [117]:
# Aggregate functions
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Sum of all elements:", np.sum(matrix))  # Output: 21
print("Maximum element:", np.max(matrix))  # Output: 6
print("Minimum element:", np.min(matrix))  # Output: 1
print("Mean of all elements:", np.mean(matrix))  # Output: 3.5

Sum of all elements: 21
Maximum element: 6
Minimum element: 1
Mean of all elements: 3.5


## Some important functions

**1. Statistical Functions:**

In [118]:
# Statistical functions
arr = np.array([1, 2, 3, 4, 5])

# Mean
result_mean = np.mean(arr)
print("Mean:", result_mean)

# Standard deviation
result_std = np.std(arr)
print("Standard Deviation:", result_std)

Mean: 3.0
Standard Deviation: 1.4142135623730951


**2. reshape:** The reshape method returns a new array with the specified shape, without changing the data.

In [119]:
# Create a one-dimensional array of 12 elements
a = np.arange(12)
print("Original array:", a)

# Reshape it to a 3x4 two-dimensional array
b = a.reshape(3,4)
print("Reshaped array:\n", b)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**3. resize:** The resize method changes the shape and size of an array in-place. This method can alter the original array and fill in with repeated copies of a if the new array is larger than the original.

In [120]:
# Resize the array in-place to 2x6
a = np.arange(10)
a.resize(2, 6)
print("Resized array:\n", a)

Resized array:
 [[0 1 2 3 4 5]
 [6 7 8 9 0 0]]


**4. ravel:** The ravel method returns a flattened one-dimensional array. It's a convenient way to convert any multi-dimensional array into a flat 1D array.

In [121]:
# Flatten the 3x4 array to a one-dimensional array
print(b)
flat = b.ravel()
print("Flattened array:", flat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**5. flatten:** Similar to ravel, but flatten returns a copy instead of a view of the original data, thus not affecting the original array.

In [122]:
# Create a copy of flattened array
print(b)
flat_copy = b.flatten()
print("Flattened array copy:", flat_copy)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array copy: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**6. np.append:** Adds elements to the end of an array.

In [123]:
# Append elements to the array
a = np.array([1, 2, 3])
appended = np.append(a, [7, 8])
print("Appended array:", appended)

Appended array: [1 2 3 7 8]


**7. np.insert:** Inserts elements at a specific position in the array.

In [124]:
# Insert elements into the array
inserted = np.insert(a, 1, [9, 10])
print("Array with inserted elements:", inserted)

Array with inserted elements: [ 1  9 10  2  3]


**8. np.delete:** Removes elements at a specific position from the array.

In [125]:
# Create a one-dimensional array
a = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
result = np.delete(a, 2)
print("Array after deleting element at index 2:", result)


# Delete multiple elements
result = np.delete(a, [0, 3])
print("Array after deleting elements at indices 0 and 3:", result)

Array after deleting element at index 2: [1 2 4 5]
Array after deleting elements at indices 0 and 3: [2 3 5]
